### ISSUE TITLE
can't save language config@light client BitShares-light_2.0.151125.exe

### ISSUE THREAD

**Issue by todasun** [cryptonomex/graphene-ui#544]
first start  enligh GUI
I swith to  chinese 
close the bitshares GUI
then open the GUI again
the GUI still English  not chinese
os:win10 64bit chinese

**Comment by svk31** [comment]
You don't need to refresh or do anything other than choose a new language from the dropdown, it then changes immediately. It works for me in Chrome on OSX, are you using the light client?

**Comment by todasun** [comment]
yes  light client BitShares-light_2.0.151125.exe

**Comment by wmbutler** [comment]
Confirmed this. Just happens on the lite client. Web client is fine.

**Comment by svk31** [comment]
I'm hoping this is related to some incorrect json or something else that has been fixed in one of the language updates. If it persists after the next update I'll try to have a look.

**Comment by wmbutler** [comment]
Moving to the test area on 1209 for now.

**Comment by todasun** [comment]
language setting  still not work  on  BitShares-light_2.0.151216.exe win10 64bit
why?

**Comment by todasun** [comment]
language setting still not work on  BitShares-light_2.0.151223.exe
